/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    franchises: Franchise;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    franchises: FranchisesSelect<false> | FranchisesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  layout: (
    | {
        /**
         * Section heading (optional)
         */
        heading?: string | null;
        /**
         * Show filter controls above the grid
         */
        showFilters?: boolean | null;
        /**
         * Only include Featured franchises
         */
        onlyFeatured?: boolean | null;
        /**
         * Only include Sponsored franchises
         */
        onlySponsored?: boolean | null;
        /**
         * Only include Top Pick franchises
         */
        onlyTopPick?: boolean | null;
        /**
         * Restrict grid to a single category (optional)
         */
        category?:
          | (
              | 'all'
              | 'Fitness'
              | 'Food and Beverage'
              | 'Health and Wellness'
              | 'Home Services'
              | 'Senior Care'
              | 'Sports'
            )
          | null;
        /**
         * Maximum number of items to show (optional)
         */
        limit?: number | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'franchiseGrid';
      }
    | {
        /**
         * The text to display in the ribbon (e.g., "Special Offer: 50% Off First Month!")
         */
        text: string;
        /**
         * Background color of the ribbon
         */
        backgroundColor: 'blue' | 'red' | 'green' | 'yellow' | 'purple' | 'orange';
        /**
         * Text color for the ribbon
         */
        textColor: 'white' | 'black';
        /**
         * Optional link to make the ribbon clickable
         */
        link: {
          /**
           * URL to navigate to when ribbon is clicked
           */
          url: string;
          /**
           * Open link in a new tab
           */
          openInNewTab?: boolean | null;
        };
        /**
         * Allow users to dismiss/close the ribbon
         */
        dismissible?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ribbon';
      }
    | {
        /**
         * Logo configuration - either image or text fallback
         */
        logo?: {
          /**
           * Logo image for the navbar
           */
          image?: (string | null) | Media;
          /**
           * Text to display if no logo image is provided (e.g., "FFO")
           */
          text?: string | null;
        };
        /**
         * Navigation menu links
         */
        navigationLinks: {
          /**
           * Display text for the navigation link
           */
          label: string;
          /**
           * URL path (e.g., "/", "/opportunities", "/contact")
           */
          url: string;
          id?: string | null;
        }[];
        /**
         * Call-to-action button configuration
         */
        ctaButton: {
          /**
           * Text for the call-to-action button
           */
          label: string;
          /**
           * URL for the CTA button
           */
          url: string;
          /**
           * Open CTA link in a new tab
           */
          openInNewTab?: boolean | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'navbar';
      }
    | {
        heading: string;
        subheading: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        image?: (string | null) | Media;
        /**
         * Call-to-action buttons (up to 5 buttons)
         */
        cta_buttons?:
          | {
              /**
               * Button text (e.g., "Discover Top Franchises", "Browse Opportunities")
               */
              label: string;
              /**
               * URL path or external link
               */
              url: string;
              /**
               * Button style - primary for main actions, secondary for alternative actions
               */
              style: 'primary' | 'secondary';
              id?: string | null;
            }[]
          | null;
        /**
         * Feature tags/badges to display below the buttons (up to 8 tags)
         */
        tags?:
          | {
              /**
               * Tag text (e.g., "Low Cost", "Home Based", "Financing Available")
               */
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage dynamic franchise listings and their metadata.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "franchises".
 */
export interface Franchise {
  id: string;
  businessName: string;
  /**
   * Optional legacy URL identifier (hidden; ID is primary)
   */
  slug?: string | null;
  /**
   * Publish lifecycle status
   */
  status?: ('draft' | 'published' | 'archived') | null;
  /**
   * Mark as featured (editorial highlight)
   */
  isFeatured?: boolean | null;
  /**
   * Mark as sponsored (paid promotion)
   */
  isSponsored?: boolean | null;
  /**
   * Mark as a top pick to highlight across the site
   */
  isTopPick?: boolean | null;
  /**
   * Detailed description using the rich text editor
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Primary business category
   */
  category: 'Fitness' | 'Food and Beverage' | 'Health and Wellness' | 'Home Services' | 'Senior Care' | 'Sports';
  /**
   * Classification tags (e.g., Low Cost, Home Based)
   */
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Initial investment range
   */
  investment?: {
    min?: number | null;
    max?: number | null;
  };
  /**
   * Franchise logo or primary image
   */
  logo?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'franchises';
        value: string | Franchise;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  id?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  id?: T;
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  id?: T;
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        franchiseGrid?:
          | T
          | {
              heading?: T;
              showFilters?: T;
              onlyFeatured?: T;
              onlySponsored?: T;
              onlyTopPick?: T;
              category?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        ribbon?:
          | T
          | {
              text?: T;
              backgroundColor?: T;
              textColor?: T;
              link?:
                | T
                | {
                    url?: T;
                    openInNewTab?: T;
                  };
              dismissible?: T;
              id?: T;
              blockName?: T;
            };
        navbar?:
          | T
          | {
              logo?:
                | T
                | {
                    image?: T;
                    text?: T;
                  };
              navigationLinks?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              ctaButton?:
                | T
                | {
                    label?: T;
                    url?: T;
                    openInNewTab?: T;
                  };
              id?: T;
              blockName?: T;
            };
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              image?: T;
              cta_buttons?:
                | T
                | {
                    label?: T;
                    url?: T;
                    style?: T;
                    id?: T;
                  };
              tags?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "franchises_select".
 */
export interface FranchisesSelect<T extends boolean = true> {
  id?: T;
  businessName?: T;
  slug?: T;
  status?: T;
  isFeatured?: T;
  isSponsored?: T;
  isTopPick?: T;
  description?: T;
  category?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  investment?:
    | T
    | {
        min?: T;
        max?: T;
      };
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}