/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    franchises: Franchise;
    industries: Industry;
    tags: Tag;
    agents: Agent;
    contactSubmissions: ContactSubmission;
    auditLogs: AuditLog;
    'mcp-tokens': McpToken;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    franchises: FranchisesSelect<false> | FranchisesSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    agents: AgentsSelect<false> | AgentsSelect<true>;
    contactSubmissions: ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    auditLogs: AuditLogsSelect<false> | AuditLogsSelect<true>;
    'mcp-tokens': McpTokensSelect<false> | McpTokensSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * URL path for this page (e.g., "franchises" for /franchises, "homepage" for /). Auto-generated from title but can be edited.
   */
  slug: string;
  layout: (
    | {
        /**
         * ✅ Published | ⬜ Unpublished (hidden from visitors)
         */
        published?: boolean | null;
        /**
         * Optional anchor ID for direct linking (e.g., "contact-form" creates #contact-form). Use lowercase letters, numbers, and hyphens only.
         */
        anchorId?: string | null;
        /**
         * Section heading (optional)
         */
        heading?: string | null;
        /**
         * Choose how franchises are selected for this grid
         */
        displayMode: 'automatic' | 'manual';
        /**
         * Manually select franchises to display (order matters)
         */
        selectedFranchises?: (string | Franchise)[] | null;
        /**
         * Show filter controls above the grid
         */
        showFilters?: boolean | null;
        /**
         * Show filter tabs (Top Pick, Sponsored, Featured) next to heading
         */
        showTabs?: boolean | null;
        /**
         * Only include Featured franchises
         */
        onlyFeatured?: boolean | null;
        /**
         * Only include Sponsored franchises
         */
        onlySponsored?: boolean | null;
        /**
         * Only include Top Pick franchises
         */
        onlyTopPick?: boolean | null;
        /**
         * Filter by specific industry (optional)
         */
        industry?: (string | null) | Industry;
        /**
         * Maximum number of items to show (optional)
         */
        limit?: number | null;
        /**
         * Show a "See All" button below the grid when items are limited
         */
        showAllButton?: boolean | null;
        /**
         * Text for the "See All" button
         */
        showAllButtonText?: string | null;
        /**
         * URL for the "See All" button (e.g., /find-a-franchise?filter=featured)
         */
        showAllButtonLink?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'franchiseGrid';
      }
    | {
        /**
         * ✅ Published | ⬜ Unpublished (hidden from visitors)
         */
        published?: boolean | null;
        /**
         * Optional anchor ID for direct linking (e.g., "contact-form" creates #contact-form). Use lowercase letters, numbers, and hyphens only.
         */
        anchorId?: string | null;
        /**
         * The text to display in the ribbon (e.g., "Special Offer: 50% Off First Month!")
         */
        text: string;
        /**
         * Background color (hex code, e.g., #2563eb for blue)
         */
        backgroundColor: string;
        /**
         * Text color (hex code, e.g., #ffffff for white)
         */
        textColor: string;
        /**
         * Font size in pixels (10-32px)
         */
        fontSize?: number | null;
        /**
         * Font weight/thickness
         */
        fontWeight?: ('300' | '400' | '500' | '600' | '700' | '800') | null;
        /**
         * Enable scrolling ticker animation
         */
        isMoving?: boolean | null;
        /**
         * Animation speed (10-200, higher = faster). Only applies when moving.
         */
        speed?: number | null;
        /**
         * Text alignment. Only applies when not moving.
         */
        textAlign?: ('left' | 'center' | 'right') | null;
        /**
         * Optional link to make the ribbon clickable
         */
        link: {
          /**
           * URL to navigate to when ribbon is clicked
           */
          url: string;
          /**
           * Open link in a new tab
           */
          openInNewTab?: boolean | null;
        };
        /**
         * Allow users to dismiss/close the ribbon
         */
        dismissible?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ribbon';
      }
    | {
        /**
         * ✅ Published | ⬜ Unpublished (hidden from visitors)
         */
        published?: boolean | null;
        /**
         * Optional anchor ID for direct linking (e.g., "contact-form" creates #contact-form). Use lowercase letters, numbers, and hyphens only.
         */
        anchorId?: string | null;
        /**
         * Logo configuration - either image or text fallback
         */
        logo?: {
          /**
           * Logo image for the navbar
           */
          image?: (string | null) | Media;
          /**
           * Text to display if no logo image is provided (e.g., "FFO")
           */
          text?: string | null;
        };
        /**
         * Navigation menu links
         */
        navigationLinks: {
          /**
           * Display text for the navigation link
           */
          label: string;
          /**
           * URL path (e.g., "/", "/opportunities", "/contact")
           */
          url: string;
          id?: string | null;
        }[];
        /**
         * Call-to-action button configuration
         */
        ctaButton: {
          /**
           * Text for the call-to-action button
           */
          label: string;
          /**
           * URL for the CTA button
           */
          url: string;
          /**
           * Open CTA link in a new tab
           */
          openInNewTab?: boolean | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'navbar';
      }
    | {
        /**
         * ✅ Published | ⬜ Unpublished (hidden from visitors)
         */
        published?: boolean | null;
        /**
         * Optional anchor ID for direct linking (e.g., "contact-form" creates #contact-form). Use lowercase letters, numbers, and hyphens only.
         */
        anchorId?: string | null;
        heading: string;
        subheading: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        /**
         * Background image for the hero section (optional)
         */
        image?: (string | null) | Media;
        /**
         * Add a dark overlay over the background image to improve contrast
         */
        showOverlay?: boolean | null;
        /**
         * Apply a soft blur to the overlay for extra readability
         */
        backgroundBlur?: boolean | null;
        /**
         * Call-to-action buttons (up to 5 buttons)
         */
        cta_buttons?:
          | {
              /**
               * Button text (e.g., "Discover Top Franchises", "Browse Opportunities")
               */
              label: string;
              /**
               * URL path or external link
               */
              url: string;
              /**
               * Button style - primary for main actions, secondary for alternative actions
               */
              style: 'primary' | 'secondary';
              id?: string | null;
            }[]
          | null;
        /**
         * Feature tags/badges to display below the buttons (up to 8 tags)
         */
        tags?:
          | {
              /**
               * Tag text (e.g., "Low Cost", "Home Based", "Financing Available")
               */
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        /**
         * ✅ Published | ⬜ Unpublished (hidden from visitors)
         */
        published?: boolean | null;
        /**
         * Optional anchor ID for direct linking (e.g., "contact-form" creates #contact-form). Use lowercase letters, numbers, and hyphens only.
         */
        anchorId?: string | null;
        /**
         * Short label shown above the heading (e.g., "Our Purpose")
         */
        eyebrow?: string | null;
        /**
         * Main section heading
         */
        heading?: string | null;
        /**
         * Supporting paragraph introducing your team and value proposition
         */
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Key differentiators, credentials, or testimonials to feature
         */
        highlights?:
          | {
              /**
               * Short highlight title (e.g., "25+ Years Advising Franchises")
               */
              title: string;
              /**
               * Optional supporting sentence elaborating on the highlight
               */
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Add one or more call-to-action buttons (optional)
         */
        ctas?:
          | {
              /**
               * Call-to-action text (e.g., "Speak to a Consultant")
               */
              label: string;
              /**
               * Call-to-action link destination
               */
              url: string;
              /**
               * Visual style for the button
               */
              style?: ('primary' | 'secondary' | 'outline' | 'ghost') | null;
              /**
               * Open the call-to-action in a new tab
               */
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional supporting image or consultant photo (replaces side card text)
         */
        image?: (string | null) | Media;
        /**
         * Show the side card/image container on the right
         */
        showSideCard?: boolean | null;
        /**
         * Side card eyebrow text (e.g., "Trusted Advisors")
         */
        sideCardEyebrow?: string | null;
        /**
         * Side card heading text
         */
        sideCardHeading?: string | null;
        /**
         * Side card description text
         */
        sideCardDescription?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'aboutTeaser';
      }
    | {
        /**
         * ✅ Published | ⬜ Unpublished (hidden from visitors)
         */
        published?: boolean | null;
        /**
         * Optional anchor ID for direct linking (e.g., "contact-form" creates #contact-form). Use lowercase letters, numbers, and hyphens only.
         */
        anchorId?: string | null;
        /**
         * Optional kicker text shown above the heading (e.g., "Let's Talk")
         */
        eyebrow?: string | null;
        /**
         * Primary CTA headline
         */
        heading?: string | null;
        /**
         * Supporting copy that reinforces the call to action
         */
        description?: string | null;
        /**
         * Control text and button alignment
         */
        alignment?: ('center' | 'left') | null;
        /**
         * Choose how the background should render
         */
        backgroundStyle?: ('color' | 'gradient' | 'image') | null;
        /**
         * Hex color used when background style is set to "Solid Color"
         */
        backgroundColor?: string | null;
        /**
         * CSS gradient value used when background style is "Gradient"
         */
        backgroundGradient?: string | null;
        /**
         * Background image used when background style is "Image"
         */
        backgroundImage?: (string | null) | Media;
        /**
         * Overlay color shown on top of image background
         */
        overlayColor?: string | null;
        /**
         * Overlay opacity (0 - 0.95). Applies to image backgrounds.
         */
        overlayOpacity?: number | null;
        /**
         * Background blur amount in pixels (0-20). Only applies to image backgrounds.
         */
        backgroundBlur?: number | null;
        /**
         * Add up to three CTA buttons
         */
        ctas?:
          | {
              /**
               * Button label (e.g., "Speak to a Consultant")
               */
              label: string;
              /**
               * Destination URL for the CTA button
               */
              url: string;
              /**
               * Button visual style
               */
              style?: ('primary' | 'secondary' | 'outline' | 'ghost') | null;
              /**
               * Open the CTA link in a new tab
               */
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional fine print or reassurance text shown below the buttons
         */
        smallPrint?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'callToAction';
      }
    | {
        /**
         * ✅ Published | ⬜ Unpublished (hidden from visitors)
         */
        published?: boolean | null;
        /**
         * Optional anchor ID for direct linking (e.g., "contact-form" creates #contact-form). Use lowercase letters, numbers, and hyphens only.
         */
        anchorId?: string | null;
        /**
         * Section heading (e.g., "Latest Insights", "Recent Articles")
         */
        heading?: string | null;
        /**
         * Optional subheading text below the main heading
         */
        subheading?: string | null;
        /**
         * RSS feed URL to fetch blog posts from
         */
        feedUrl?: string | null;
        /**
         * Display posts in a carousel slider or a responsive grid
         */
        displayMode?: ('carousel' | 'grid') | null;
        /**
         * Maximum number of blog posts to display (1-30)
         */
        limit?: number | null;
        /**
         * Display author information on each post
         */
        showAuthor?: boolean | null;
        /**
         * Display publication date on each post
         */
        showDate?: boolean | null;
        /**
         * Display estimated reading time on each post
         */
        showReadTime?: boolean | null;
        /**
         * URL for the "View All Posts" button (e.g., link to your full blog)
         */
        viewAllLink?: string | null;
        /**
         * Show the "View All Posts" button at the bottom
         */
        showViewAllButton?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'blogHighlights';
      }
    | {
        /**
         * ✅ Published | ⬜ Unpublished (hidden from visitors)
         */
        published?: boolean | null;
        /**
         * Optional anchor ID for direct linking (e.g., "contact-form" creates #contact-form). Use lowercase letters, numbers, and hyphens only.
         */
        anchorId?: string | null;
        /**
         * Section heading (e.g., "Explore Our Locations", "Find Opportunities")
         */
        heading?: string | null;
        /**
         * Optional description text below the heading
         */
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Google Maps embed URL (from Google My Maps)
         */
        mapUrl?: string | null;
        /**
         * Map height in pixels (300-800)
         */
        height?: number | null;
        /**
         * Show "View Full Map" button below the map
         */
        showViewButton?: boolean | null;
        /**
         * Custom text for the "View Full Map" button
         */
        buttonText?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'map';
      }
    | {
        /**
         * ✅ Published | ⬜ Unpublished (hidden from visitors)
         */
        published?: boolean | null;
        /**
         * Optional anchor ID for direct linking (e.g., "contact-form" creates #contact-form). Use lowercase letters, numbers, and hyphens only.
         */
        anchorId?: string | null;
        /**
         * Section heading (e.g., "Our Team", "Meet the Experts")
         */
        heading?: string | null;
        /**
         * Optional subheading text below the main heading
         */
        subheading?: string | null;
        /**
         * Choose how team members are displayed
         */
        layoutMode: 'grid' | 'carousel';
        /**
         * Add team members to display (up to 50 members)
         */
        teamMembers?:
          | {
              /**
               * Team member photo (optional - will show initials if not provided)
               */
              photo?: (string | null) | Media;
              /**
               * Team member full name
               */
              name: string;
              /**
               * Job title or role (e.g., "Senior Consultant", "CEO")
               */
              title?: string | null;
              /**
               * Location (e.g., "New York, NY", "Remote", "San Francisco")
               */
              location?: string | null;
              /**
               * Team member biography with support for links and formatting
               */
              biography?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'teamSection';
      }
    | {
        /**
         * ✅ Published | ⬜ Unpublished (hidden from visitors)
         */
        published?: boolean | null;
        /**
         * Optional anchor ID for direct linking (e.g., "contact-form" creates #contact-form). Use lowercase letters, numbers, and hyphens only.
         */
        anchorId?: string | null;
        /**
         * Form heading (e.g., "Contact Us", "Request Information")
         */
        heading?: string | null;
        /**
         * Optional description text above the form
         */
        description?: string | null;
        /**
         * Add and configure form fields - drag to reorder
         */
        formFields: {
          /**
           * Type of input field
           */
          fieldType: 'text' | 'email' | 'tel' | 'number' | 'textarea' | 'select';
          /**
           * Field label (e.g., "Full Name", "Email Address")
           */
          label: string;
          /**
           * Field name for form data (e.g., "fullName", "email") - use camelCase, no spaces
           */
          name: string;
          /**
           * Optional placeholder text
           */
          placeholder?: string | null;
          /**
           * Make this field required
           */
          required?: boolean | null;
          /**
           * Field width - use half or third for side-by-side fields
           */
          width: 'full' | 'half' | 'third';
          /**
           * Options for select dropdown (only used when field type is Select)
           */
          options?:
            | {
                label: string;
                value: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[];
        /**
         * Text for the submit button
         */
        submitButtonText?: string | null;
        /**
         * Message shown after successful form submission
         */
        successMessage?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'formBuilder';
      }
    | {
        /**
         * ✅ Published | ⬜ Unpublished (hidden from visitors)
         */
        published?: boolean | null;
        /**
         * Optional anchor ID for direct linking (e.g., "contact-form" creates #contact-form). Use lowercase letters, numbers, and hyphens only.
         */
        anchorId?: string | null;
        /**
         * Section heading (e.g., "Reach Us", "Get in Touch")
         */
        heading?: string | null;
        contactDetails?: {
          /**
           * Show phone number
           */
          showPhone?: boolean | null;
          /**
           * Phone number (e.g., "(555) 123-4567")
           */
          phone?: string | null;
          /**
           * Show email address
           */
          showEmail?: boolean | null;
          /**
           * Email address
           */
          email?: string | null;
          /**
           * Show physical address
           */
          showAddress?: boolean | null;
          /**
           * Physical address (use line breaks for formatting)
           */
          address?: string | null;
          /**
           * Show business hours
           */
          showHours?: boolean | null;
          /**
           * Business hours (use line breaks for formatting)
           */
          hours?: string | null;
        };
        /**
         * Show embedded map
         */
        showMap?: boolean | null;
        /**
         * Google Maps embed URL
         */
        mapUrl?: string | null;
        /**
         * Map height in pixels (200-600)
         */
        mapHeight?: number | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contactInfo';
      }
    | {
        /**
         * ✅ Published | ⬜ Unpublished (hidden from visitors)
         */
        published?: boolean | null;
        /**
         * Optional anchor ID for direct linking (e.g., "contact-form" creates #contact-form). Use lowercase letters, numbers, and hyphens only.
         */
        anchorId?: string | null;
        /**
         * Main heading text
         */
        heading?: string | null;
        /**
         * Content text (supports multiple paragraphs)
         */
        content?: string | null;
        /**
         * Image to display
         */
        image?: (string | null) | Media;
        /**
         * Choose which side to display the image
         */
        imagePosition?: ('left' | 'right') | null;
        /**
         * Button text (optional)
         */
        buttonText?: string | null;
        /**
         * Button link URL (optional)
         */
        buttonLink?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contentImage';
      }
    | {
        /**
         * ✅ Published | ⬜ Unpublished (hidden from visitors)
         */
        published?: boolean | null;
        /**
         * Optional anchor ID for direct linking (e.g., "contact-form" creates #contact-form). Use lowercase letters, numbers, and hyphens only.
         */
        anchorId?: string | null;
        /**
         * Add cards to display in a grid (up to 12 cards)
         */
        cards?:
          | {
              /**
               * Card title
               */
              title: string;
              /**
               * Card content text
               */
              content?: string | null;
              /**
               * Card background color (hex code)
               */
              backgroundColor?: string | null;
              /**
               * Card text color (hex code)
               */
              textColor?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Button text below the grid (optional)
         */
        buttonText?: string | null;
        /**
         * Button link URL (optional)
         */
        buttonLink?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'gridCards';
      }
    | {
        /**
         * ✅ Published | ⬜ Unpublished (hidden from visitors)
         */
        published?: boolean | null;
        /**
         * Optional anchor ID for direct linking (e.g., "contact-form" creates #contact-form). Use lowercase letters, numbers, and hyphens only.
         */
        anchorId?: string | null;
        /**
         * Choose video source type
         */
        videoType: 'link' | 'upload';
        /**
         * YouTube or Vimeo video URL
         */
        videoUrl?: string | null;
        /**
         * Upload a video file
         */
        videoFile?: (string | null) | Media;
        /**
         * Button text below the video (optional)
         */
        buttonText?: string | null;
        /**
         * Button link URL (optional)
         */
        buttonLink?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'video';
      }
    | {
        /**
         * ✅ Published | ⬜ Unpublished (hidden from visitors)
         */
        published?: boolean | null;
        /**
         * Optional anchor ID for direct linking (e.g., "contact-form" creates #contact-form). Use lowercase letters, numbers, and hyphens only.
         */
        anchorId?: string | null;
        /**
         * Section heading (optional)
         */
        heading?: string | null;
        /**
         * Add as many image cards as you want
         */
        cards: {
          /**
           * Card image
           */
          image: string | Media;
          /**
           * Card title (optional)
           */
          title?: string | null;
          /**
           * Card description (optional)
           */
          description?: string | null;
          /**
           * Button text (optional)
           */
          buttonText?: string | null;
          /**
           * Button link URL (optional)
           */
          buttonLink?: string | null;
          id?: string | null;
        }[];
        /**
         * Number of cards to show initially (default: 6)
         */
        initialCardsToShow?: number | null;
        /**
         * Number of cards to load when "Show More" is clicked (default: 6)
         */
        cardsPerLoad?: number | null;
        /**
         * Text for the "Show More" button
         */
        showMoreButtonText?: string | null;
        /**
         * Number of columns in the grid
         */
        columns?: ('1' | '2' | '3' | '4') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'imageCard';
      }
    | {
        /**
         * ✅ Published | ⬜ Unpublished (hidden from visitors)
         */
        published?: boolean | null;
        /**
         * Optional anchor ID for direct linking (e.g., "contact-form" creates #contact-form). Use lowercase letters, numbers, and hyphens only.
         */
        anchorId?: string | null;
        /**
         * Section heading (e.g., "Free Resources", "Downloads")
         */
        heading?: string | null;
        /**
         * Optional subheading text below the main heading
         */
        subheading?: string | null;
        /**
         * Maximum number of columns in the grid
         */
        columns?: ('2' | '3' | '4' | '5') | null;
        /**
         * Add resource cards (up to 20)
         */
        resources?:
          | {
              /**
               * Resource image (optional)
               */
              image?: (string | null) | Media;
              /**
               * URL to link the image to (optional)
               */
              imageLink?: string | null;
              /**
               * Open image link in a new tab
               */
              imageLinkOpenInNewTab?: boolean | null;
              /**
               * Resource title (optional)
               */
              title?: string | null;
              /**
               * Resource description (optional)
               */
              content?: string | null;
              /**
               * Button text (optional, e.g., "Download Your PDF")
               */
              buttonText?: string | null;
              /**
               * What happens when the button is clicked
               */
              buttonAction?: ('link' | 'popup') | null;
              /**
               * Button URL (required if action is "Open Link")
               */
              buttonUrl?: string | null;
              /**
               * Open button link in a new tab
               */
              buttonOpenInNewTab?: boolean | null;
              /**
               * Popup heading text
               */
              popupHeading?: string | null;
              /**
               * Popup submit button text
               */
              popupSubmitText?: string | null;
              /**
               * Message shown after successful submission
               */
              popupSuccessMessage?: string | null;
              /**
               * URL to the downloadable file (sent via email or shown after submission)
               */
              popupDownloadUrl?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Section background color (hex code)
         */
        backgroundColor?: string | null;
        /**
         * Card background color (hex code)
         */
        cardBackgroundColor?: string | null;
        /**
         * Text color (hex code)
         */
        textColor?: string | null;
        /**
         * Button style for all resource cards
         */
        buttonStyle?: ('primary' | 'secondary' | 'outline') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'resourcesGrid';
      }
  )[];
  seo?: {
    /**
     * SEO title (50-60 characters). Leave empty to use page title + site name.
     */
    metaTitle?: string | null;
    /**
     * SEO description (150-160 characters). Appears in search results. Leave empty to use site default.
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords for this page (e.g., "food franchises, restaurant opportunities"). Leave empty to use site defaults.
     */
    keywords?: string | null;
    /**
     * Image for social media sharing (1200x630px recommended). Leave empty to use site default.
     */
    ogImage?: (string | null) | Media;
    /**
     * ⚠️ Check to prevent search engines from indexing this page (useful for draft/private pages)
     */
    noIndex?: boolean | null;
  };
  /**
   * User who created this record
   */
  createdBy?: (string | null) | User;
  /**
   * User who last updated this record
   */
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage dynamic franchise listings and their metadata.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "franchises".
 */
export interface Franchise {
  id: string;
  businessName: string;
  /**
   * Optional legacy URL identifier (hidden; ID is primary)
   */
  slug?: string | null;
  /**
   * Publish lifecycle status
   */
  status?: ('draft' | 'published' | 'archived') | null;
  /**
   * ⭐ Mark as featured (editorial highlight) - Shows "Featured" badge on card
   */
  isFeatured?: boolean | null;
  /**
   * 💰 Mark as sponsored (paid promotion) - Shows "Sponsored" badge on card
   */
  isSponsored?: boolean | null;
  /**
   * ⭐ Mark as a top pick - Shows "⭐ Top Pick" badge on card
   */
  isTopPick?: boolean | null;
  /**
   * Brief summary - Used for cards, previews, and SEO meta descriptions.
   */
  shortDescription?: string | null;
  /**
   * Full detailed description with support for links to pages and franchises. Paste HTML for advanced formatting.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Industries/categories for this franchise (can select multiple)
   */
  industry?: (string | Industry)[] | null;
  /**
   * Feature tags (e.g., Low Cost, Home Based, Financing Available)
   */
  tags?: (string | Tag)[] | null;
  /**
   * Initial investment range
   */
  investment?: {
    min?: number | null;
    max?: number | null;
    /**
     * Custom background color for the "Cash Required" badge (hex code) - Leave empty for default
     */
    badgeColor?: string | null;
    /**
     * Badge text color (hex code) - Only used when background color is set. Default is white (#ffffff)
     */
    badgeTextColor?: string | null;
  };
  /**
   * Franchise logo or primary image
   */
  logo?: (string | null) | Media;
  /**
   * Assign a specific agent to this franchise (optional). If not assigned, inquiries go to main contact.
   */
  assignedAgent?: (string | null) | Agent;
  /**
   * Force use main contact even if agent is assigned (overrides agent assignment)
   */
  useMainContact?: boolean | null;
  /**
   * Also send a copy to the main contact email when sending to the assigned agent
   */
  ccMainContact?: boolean | null;
  /**
   * User who created this record
   */
  createdBy?: (string | null) | User;
  /**
   * User who last updated this record
   */
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: string;
  /**
   * Industry name (e.g., "Food & Beverage", "Fitness")
   */
  name: string;
  /**
   * URL-friendly version (auto-generated from name)
   */
  slug: string;
  /**
   * Optional description of this industry category
   */
  description?: string | null;
  /**
   * Choose an icon to represent this industry
   */
  icon?:
    | (
        | 'Briefcase'
        | 'Dumbbell'
        | 'Coffee'
        | 'UtensilsCrossed'
        | 'Home'
        | 'Wrench'
        | 'Heart'
        | 'Stethoscope'
        | 'Users'
        | 'Activity'
        | 'Sparkles'
        | 'HardHat'
        | 'BookOpen'
        | 'Baby'
        | 'PawPrint'
        | 'Car'
        | 'Sparkle'
        | 'DollarSign'
        | 'Store'
        | 'Package'
        | 'Palette'
        | 'Smartphone'
        | 'Building2'
        | 'Plane'
        | 'Music'
      )
    | null;
  /**
   * Badge background color (hex code) - Leave empty for default light gray
   */
  color?: string | null;
  /**
   * Badge text color (hex code) - Only used when background color is set. Default is white (#ffffff)
   */
  textColor?: string | null;
  /**
   * User who created this record
   */
  createdBy?: (string | null) | User;
  /**
   * User who last updated this record
   */
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  /**
   * Tag name (e.g., "Low Cost", "Home Based", "Financing Available")
   */
  name: string;
  /**
   * URL-friendly version (auto-generated from name)
   */
  slug: string;
  /**
   * Categorize the tag for better organization
   */
  type?: ('feature' | 'investment' | 'model' | 'location' | 'other') | null;
  /**
   * Optional description of this tag
   */
  description?: string | null;
  /**
   * Badge background color (hex code) - Leave empty for default light gray
   */
  color?: string | null;
  /**
   * Badge text color (hex code) - Only used when background color is set. Default is white (#ffffff)
   */
  textColor?: string | null;
  /**
   * User who created this record
   */
  createdBy?: (string | null) | User;
  /**
   * User who last updated this record
   */
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage franchise consultants and agents
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents".
 */
export interface Agent {
  id: string;
  name: string;
  email: string;
  phone?: string | null;
  title?: string | null;
  /**
   * Agent biography with support for links to pages and franchises. Paste HTML for advanced formatting.
   */
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  photo?: (string | null) | Media;
  /**
   * Franchise categories or specialties
   */
  specialties?:
    | {
        category?:
          | ('Fitness' | 'Food and Beverage' | 'Health and Wellness' | 'Home Services' | 'Senior Care' | 'Sports')
          | null;
        id?: string | null;
      }[]
    | null;
  isActive?: boolean | null;
  /**
   * GoHighLevel webhook URL (optional)
   */
  ghlWebhook?: string | null;
  /**
   * User who created this record
   */
  createdBy?: (string | null) | User;
  /**
   * User who last updated this record
   */
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contact form submissions from site visitors
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactSubmissions".
 */
export interface ContactSubmission {
  id: string;
  /**
   * Submitter name
   */
  name?: string | null;
  /**
   * Submitter email address
   */
  email?: string | null;
  /**
   * Submitter phone number
   */
  phone?: string | null;
  /**
   * Company name
   */
  company?: string | null;
  /**
   * Message subject
   */
  subject?: string | null;
  /**
   * Message content
   */
  message?: string | null;
  /**
   * Submitter IP address (captured automatically)
   */
  ipAddress?: string | null;
  /**
   * Submission status for tracking and organization
   */
  status: 'new' | 'read' | 'archived';
  /**
   * User who created this record
   */
  createdBy?: (string | null) | User;
  /**
   * User who last updated this record
   */
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * System-wide activity log tracking all changes
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auditLogs".
 */
export interface AuditLog {
  id: string;
  /**
   * Which collection was modified
   */
  collection: string;
  /**
   * ID of the record that was modified
   */
  recordId: string;
  /**
   * Type of operation performed
   */
  operation: 'create' | 'update' | 'delete';
  /**
   * User who performed the action
   */
  user?: (string | null) | User;
  /**
   * Detailed changes (before/after values)
   */
  changes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * List of fields that were modified
   */
  changedFields?:
    | {
        field: string;
        id?: string | null;
      }[]
    | null;
  /**
   * IP address of the user
   */
  ipAddress?: string | null;
  /**
   * Browser/client information
   */
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * MCP API tokens. User-linked tokens impersonate the user; service/admin tokens use scopes only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mcp-tokens".
 */
export interface McpToken {
  id: string;
  label: string;
  type: 'user' | 'service' | 'admin';
  user?: (string | null) | User;
  /**
   * Custom scopes for this token. Leave empty to use default scopes based on token type. Format: collections:{collection}:{operation} (e.g., collections:users:read, collections:media:create) or media:upload, mcp:describe. Use collections:*:* for full access.
   */
  scopes?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  active?: boolean | null;
  expiresAt?: string | null;
  tokenHash: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'franchises';
        value: string | Franchise;
      } | null)
    | ({
        relationTo: 'industries';
        value: string | Industry;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'agents';
        value: string | Agent;
      } | null)
    | ({
        relationTo: 'contactSubmissions';
        value: string | ContactSubmission;
      } | null)
    | ({
        relationTo: 'auditLogs';
        value: string | AuditLog;
      } | null)
    | ({
        relationTo: 'mcp-tokens';
        value: string | McpToken;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        franchiseGrid?:
          | T
          | {
              published?: T;
              anchorId?: T;
              heading?: T;
              displayMode?: T;
              selectedFranchises?: T;
              showFilters?: T;
              showTabs?: T;
              onlyFeatured?: T;
              onlySponsored?: T;
              onlyTopPick?: T;
              industry?: T;
              limit?: T;
              showAllButton?: T;
              showAllButtonText?: T;
              showAllButtonLink?: T;
              id?: T;
              blockName?: T;
            };
        ribbon?:
          | T
          | {
              published?: T;
              anchorId?: T;
              text?: T;
              backgroundColor?: T;
              textColor?: T;
              fontSize?: T;
              fontWeight?: T;
              isMoving?: T;
              speed?: T;
              textAlign?: T;
              link?:
                | T
                | {
                    url?: T;
                    openInNewTab?: T;
                  };
              dismissible?: T;
              id?: T;
              blockName?: T;
            };
        navbar?:
          | T
          | {
              published?: T;
              anchorId?: T;
              logo?:
                | T
                | {
                    image?: T;
                    text?: T;
                  };
              navigationLinks?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              ctaButton?:
                | T
                | {
                    label?: T;
                    url?: T;
                    openInNewTab?: T;
                  };
              id?: T;
              blockName?: T;
            };
        hero?:
          | T
          | {
              published?: T;
              anchorId?: T;
              heading?: T;
              subheading?: T;
              image?: T;
              showOverlay?: T;
              backgroundBlur?: T;
              cta_buttons?:
                | T
                | {
                    label?: T;
                    url?: T;
                    style?: T;
                    id?: T;
                  };
              tags?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        aboutTeaser?:
          | T
          | {
              published?: T;
              anchorId?: T;
              eyebrow?: T;
              heading?: T;
              description?: T;
              highlights?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              ctas?:
                | T
                | {
                    label?: T;
                    url?: T;
                    style?: T;
                    openInNewTab?: T;
                    id?: T;
                  };
              image?: T;
              showSideCard?: T;
              sideCardEyebrow?: T;
              sideCardHeading?: T;
              sideCardDescription?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              published?: T;
              anchorId?: T;
              eyebrow?: T;
              heading?: T;
              description?: T;
              alignment?: T;
              backgroundStyle?: T;
              backgroundColor?: T;
              backgroundGradient?: T;
              backgroundImage?: T;
              overlayColor?: T;
              overlayOpacity?: T;
              backgroundBlur?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    url?: T;
                    style?: T;
                    openInNewTab?: T;
                    id?: T;
                  };
              smallPrint?: T;
              id?: T;
              blockName?: T;
            };
        blogHighlights?:
          | T
          | {
              published?: T;
              anchorId?: T;
              heading?: T;
              subheading?: T;
              feedUrl?: T;
              displayMode?: T;
              limit?: T;
              showAuthor?: T;
              showDate?: T;
              showReadTime?: T;
              viewAllLink?: T;
              showViewAllButton?: T;
              id?: T;
              blockName?: T;
            };
        map?:
          | T
          | {
              published?: T;
              anchorId?: T;
              heading?: T;
              description?: T;
              mapUrl?: T;
              height?: T;
              showViewButton?: T;
              buttonText?: T;
              id?: T;
              blockName?: T;
            };
        teamSection?:
          | T
          | {
              published?: T;
              anchorId?: T;
              heading?: T;
              subheading?: T;
              layoutMode?: T;
              teamMembers?:
                | T
                | {
                    photo?: T;
                    name?: T;
                    title?: T;
                    location?: T;
                    biography?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        formBuilder?:
          | T
          | {
              published?: T;
              anchorId?: T;
              heading?: T;
              description?: T;
              formFields?:
                | T
                | {
                    fieldType?: T;
                    label?: T;
                    name?: T;
                    placeholder?: T;
                    required?: T;
                    width?: T;
                    options?:
                      | T
                      | {
                          label?: T;
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              submitButtonText?: T;
              successMessage?: T;
              id?: T;
              blockName?: T;
            };
        contactInfo?:
          | T
          | {
              published?: T;
              anchorId?: T;
              heading?: T;
              contactDetails?:
                | T
                | {
                    showPhone?: T;
                    phone?: T;
                    showEmail?: T;
                    email?: T;
                    showAddress?: T;
                    address?: T;
                    showHours?: T;
                    hours?: T;
                  };
              showMap?: T;
              mapUrl?: T;
              mapHeight?: T;
              id?: T;
              blockName?: T;
            };
        contentImage?:
          | T
          | {
              published?: T;
              anchorId?: T;
              heading?: T;
              content?: T;
              image?: T;
              imagePosition?: T;
              buttonText?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        gridCards?:
          | T
          | {
              published?: T;
              anchorId?: T;
              cards?:
                | T
                | {
                    title?: T;
                    content?: T;
                    backgroundColor?: T;
                    textColor?: T;
                    id?: T;
                  };
              buttonText?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              published?: T;
              anchorId?: T;
              videoType?: T;
              videoUrl?: T;
              videoFile?: T;
              buttonText?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        imageCard?:
          | T
          | {
              published?: T;
              anchorId?: T;
              heading?: T;
              cards?:
                | T
                | {
                    image?: T;
                    title?: T;
                    description?: T;
                    buttonText?: T;
                    buttonLink?: T;
                    id?: T;
                  };
              initialCardsToShow?: T;
              cardsPerLoad?: T;
              showMoreButtonText?: T;
              columns?: T;
              id?: T;
              blockName?: T;
            };
        resourcesGrid?:
          | T
          | {
              published?: T;
              anchorId?: T;
              heading?: T;
              subheading?: T;
              columns?: T;
              resources?:
                | T
                | {
                    image?: T;
                    imageLink?: T;
                    imageLinkOpenInNewTab?: T;
                    title?: T;
                    content?: T;
                    buttonText?: T;
                    buttonAction?: T;
                    buttonUrl?: T;
                    buttonOpenInNewTab?: T;
                    popupHeading?: T;
                    popupSubmitText?: T;
                    popupSuccessMessage?: T;
                    popupDownloadUrl?: T;
                    id?: T;
                  };
              backgroundColor?: T;
              cardBackgroundColor?: T;
              textColor?: T;
              buttonStyle?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
        noIndex?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "franchises_select".
 */
export interface FranchisesSelect<T extends boolean = true> {
  businessName?: T;
  slug?: T;
  status?: T;
  isFeatured?: T;
  isSponsored?: T;
  isTopPick?: T;
  shortDescription?: T;
  description?: T;
  industry?: T;
  tags?: T;
  investment?:
    | T
    | {
        min?: T;
        max?: T;
        badgeColor?: T;
        badgeTextColor?: T;
      };
  logo?: T;
  assignedAgent?: T;
  useMainContact?: T;
  ccMainContact?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  color?: T;
  textColor?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  description?: T;
  color?: T;
  textColor?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents_select".
 */
export interface AgentsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  title?: T;
  bio?: T;
  photo?: T;
  specialties?:
    | T
    | {
        category?: T;
        id?: T;
      };
  isActive?: T;
  ghlWebhook?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactSubmissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  subject?: T;
  message?: T;
  ipAddress?: T;
  status?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auditLogs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  collection?: T;
  recordId?: T;
  operation?: T;
  user?: T;
  changes?: T;
  changedFields?:
    | T
    | {
        field?: T;
        id?: T;
      };
  ipAddress?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mcp-tokens_select".
 */
export interface McpTokensSelect<T extends boolean = true> {
  label?: T;
  type?: T;
  user?: T;
  scopes?:
    | T
    | {
        value?: T;
        id?: T;
      };
  active?: T;
  expiresAt?: T;
  tokenHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  /**
   * ✅ Published | ⬜ Unpublished (hidden from all pages)
   */
  navbarPublished?: boolean | null;
  /**
   * Control where the navbar appears
   */
  navbarVisibility?: ('all' | 'include' | 'exclude') | null;
  /**
   * Select pages to include or exclude based on visibility setting above
   */
  navbarPages?: (string | Page)[] | null;
  navbar?: {
    /**
     * Logo image for the navbar
     */
    logo?: (string | null) | Media;
    /**
     * Text to display if no logo is uploaded
     */
    logoText?: string | null;
    /**
     * Navigation links
     */
    links?:
      | {
          label: string;
          url: string;
          openInNewTab?: boolean | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional call-to-action button
     */
    ctaButton?: {
      enabled?: boolean | null;
      label?: string | null;
      url?: string | null;
    };
  };
  /**
   * ✅ Published | ⬜ Unpublished (hidden from all pages)
   */
  footerPublished?: boolean | null;
  /**
   * Control where the footer appears
   */
  footerVisibility?: ('all' | 'include' | 'exclude') | null;
  /**
   * Select pages to include or exclude based on visibility setting above
   */
  footerPages?: (string | Page)[] | null;
  footer?: {
    /**
     * Logo image for the footer (optional)
     */
    logo?: (string | null) | Media;
    /**
     * Company name displayed in footer
     */
    companyName?: string | null;
    /**
     * Tagline or description
     */
    tagline?: string | null;
    /**
     * Custom copyright text (leave empty for auto-generated)
     */
    copyrightText?: string | null;
    /**
     * Display social media links
     */
    showSocialLinks?: boolean | null;
    /**
     * Add your social media links - icons will be displayed automatically
     */
    socialLinks?:
      | {
          /**
           * Select the social media platform
           */
          platform:
            | 'facebook'
            | 'twitter'
            | 'instagram'
            | 'linkedin'
            | 'youtube'
            | 'tiktok'
            | 'pinterest'
            | 'reddit'
            | 'discord'
            | 'slack'
            | 'github'
            | 'gitlab'
            | 'twitch'
            | 'whatsapp'
            | 'telegram'
            | 'mail'
            | 'globe';
          /**
           * Full URL to your social media profile
           */
          url: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Footer navigation columns
     */
    footerColumns?:
      | {
          heading: string;
          links: {
            label: string;
            url: string;
            openInNewTab?: boolean | null;
            id?: string | null;
          }[];
          id?: string | null;
        }[]
      | null;
    /**
     * Links in the bottom bar (e.g., Privacy Policy, Terms)
     */
    bottomLinks?:
      | {
          label: string;
          url: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Footer background color (hex code)
     */
    backgroundColor?: string | null;
    /**
     * Use gradient background instead of solid color
     */
    useGradient?: boolean | null;
    /**
     * Gradient start color (hex code)
     */
    gradientFrom?: string | null;
    /**
     * Gradient end color (hex code)
     */
    gradientTo?: string | null;
    /**
     * Gradient direction
     */
    gradientDirection?: ('to-b' | 'to-t' | 'to-r' | 'to-l' | 'to-br' | 'to-bl') | null;
    /**
     * Footer text color (hex code)
     */
    textColor?: string | null;
    /**
     * Optional background image for the footer
     */
    backgroundImage?: (string | null) | Media;
    /**
     * Background image blur amount in pixels (0-20)
     */
    backgroundBlur?: number | null;
    /**
     * Overlay color on top of background image (hex code)
     */
    overlayColor?: string | null;
    /**
     * Overlay opacity (0 - 0.95)
     */
    overlayOpacity?: number | null;
  };
  /**
   * ✅ Show ticker on all pages | ⬜ Hide ticker
   */
  tickerEnabled?: boolean | null;
  ticker?: {
    /**
     * The text to display in the ticker
     */
    text: string;
    /**
     * Background color (hex code)
     */
    backgroundColor?: string | null;
    /**
     * Text color (hex code)
     */
    textColor?: string | null;
    /**
     * Font size in pixels (10-32px)
     */
    fontSize?: number | null;
    /**
     * Font weight/thickness
     */
    fontWeight?: ('300' | '400' | '500' | '600' | '700' | '800') | null;
    /**
     * Enable scrolling ticker animation
     */
    isMoving?: boolean | null;
    /**
     * Animation speed (10-200, higher = faster)
     */
    speed?: number | null;
    /**
     * Text alignment (only when not moving)
     */
    textAlign?: ('left' | 'center' | 'right') | null;
    /**
     * Optional link to make the ticker clickable
     */
    link?: {
      /**
       * URL to navigate to when ticker is clicked (optional)
       */
      url?: string | null;
      /**
       * Open link in a new tab
       */
      openInNewTab?: boolean | null;
    };
    /**
     * Allow users to dismiss/close the ticker
     */
    dismissible?: boolean | null;
  };
  /**
   * ✅ Enable floating cart button | ⬜ Disable cart feature site-wide
   */
  enableCart?: boolean | null;
  /**
   * ✅ Show wishlist button on franchise cards | ⬜ Hide wishlist button
   */
  showWishlistButton?: boolean | null;
  /**
   * ✅ Show cart button on franchise cards | ⬜ Hide cart button
   */
  showCartButton?: boolean | null;
  /**
   * Site name used in meta tags
   */
  siteName?: string | null;
  /**
   * Default site description for SEO
   */
  siteDescription?: string | null;
  /**
   * Contact email for the site
   */
  contactEmail?: string | null;
  /**
   * Contact phone number
   */
  contactPhone?: string | null;
  seo?: {
    /**
     * Default SEO title (50-60 characters). Used when pages don't have a custom title.
     */
    defaultTitle?: string | null;
    /**
     * Default meta description (150-160 characters). Appears in search results.
     */
    defaultDescription?: string | null;
    /**
     * Default keywords (comma-separated). Used for pages without specific keywords.
     */
    keywords?: string | null;
    /**
     * Default social share image (1200x630px recommended). Used when pages don't have a custom image.
     */
    ogImage?: (string | null) | Media;
    /**
     * Twitter/X handle (e.g., @yourhandle) for Twitter Card metadata
     */
    twitterHandle?: string | null;
    /**
     * Facebook App ID for Facebook Open Graph
     */
    facebookAppId?: string | null;
    /**
     * Google Search Console verification code (from <meta name="google-site-verification" content="...">)
     */
    googleSiteVerification?: string | null;
    /**
     * Bing Webmaster Tools verification code (from <meta name="msvalidate.01" content="...">)
     */
    bingSiteVerification?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  navbarPublished?: T;
  navbarVisibility?: T;
  navbarPages?: T;
  navbar?:
    | T
    | {
        logo?: T;
        logoText?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
              id?: T;
            };
        ctaButton?:
          | T
          | {
              enabled?: T;
              label?: T;
              url?: T;
            };
      };
  footerPublished?: T;
  footerVisibility?: T;
  footerPages?: T;
  footer?:
    | T
    | {
        logo?: T;
        companyName?: T;
        tagline?: T;
        copyrightText?: T;
        showSocialLinks?: T;
        socialLinks?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
        footerColumns?:
          | T
          | {
              heading?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    openInNewTab?: T;
                    id?: T;
                  };
              id?: T;
            };
        bottomLinks?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        backgroundColor?: T;
        useGradient?: T;
        gradientFrom?: T;
        gradientTo?: T;
        gradientDirection?: T;
        textColor?: T;
        backgroundImage?: T;
        backgroundBlur?: T;
        overlayColor?: T;
        overlayOpacity?: T;
      };
  tickerEnabled?: T;
  ticker?:
    | T
    | {
        text?: T;
        backgroundColor?: T;
        textColor?: T;
        fontSize?: T;
        fontWeight?: T;
        isMoving?: T;
        speed?: T;
        textAlign?: T;
        link?:
          | T
          | {
              url?: T;
              openInNewTab?: T;
            };
        dismissible?: T;
      };
  enableCart?: T;
  showWishlistButton?: T;
  showCartButton?: T;
  siteName?: T;
  siteDescription?: T;
  contactEmail?: T;
  contactPhone?: T;
  seo?:
    | T
    | {
        defaultTitle?: T;
        defaultDescription?: T;
        keywords?: T;
        ogImage?: T;
        twitterHandle?: T;
        facebookAppId?: T;
        googleSiteVerification?: T;
        bingSiteVerification?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}